### ISSUE TITLE
TransactionScope issue

### ISSUE THREAD

**Issue by mouradchama** [rebus-org/Rebus.TransactionScopes#11]
Hi,

Based on the example that works file I tried to adapted it to my situation.
I'm using an abstraction to send/publish my messages using Rebus, this is my publisher:
`public class BusPublisher : IBusPublisher
    {
        private readonly IBus _rebus;
        private TransactionScope _transactionScope;

        public BusPublisher(IBus rebus)
        {
            _rebus = rebus;
        }

        public Task PublishAsync(object message, CancellationToken token = default)
        {
            return _rebus.Publish(message);
        }

        public async Task SendAsync(object command, CancellationToken token = default)
        {
            await _rebus.Send(command);
        }

        public Task BeginTransactionAsync()
        {
            //Check if we are already inside RebusTransaction
            //If yes we keep it, otherwise we create a new transaction
            if (AmbientTransactionContext.Current == null)
            {
                _transactionScope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
                _transactionScope = _transactionScope.EnlistRebus();
            }

            return Task.CompletedTask;
        }

        public Task CommitAsync(CancellationToken token = default)
        {
            _transactionScope?.Complete();
            return Task.CompletedTask;
        }

        protected override void OnDispose()
        {
            _transactionScope?.Dispose();
        }
    }`

Usage:

`var publisher = new BusPublisher(rebus);
await publisher.BeginTransactionAsync();
await publisher.SendAsync(myCommand);
await publisher.CommitAsync();`

My command is sent to the Queue before commiting the transaction.

Maybe the TransactionScope instantiation and sending the message are not in the same code bloc? (same thread)

Thank you in advance.

**Comment by mookid8000** [comment]
Could you check out [this test](https://github.com/rebus-org/Rebus.TransactionScopes/blob/master/Rebus.TransactionScopes.Tests/TestClientTransactionScope.cs#L46) and see in what way your code differs from it?
The test verifies that Rebus enlists as it should in `TransactionScope`

**Comment by mouradchama** [comment]
Your test works, but not with my abstraction, I kept only the failing test (1 scenario)

`[TestFixture]
    public class TestClientTransactionScope_PublisherWithIssue : FixtureBase
    {
        BuiltinHandlerActivator _activator;
        IBusStarter _starter;

        protected override void SetUp()
        {
            _activator = new BuiltinHandlerActivator();

            Using(_activator);

            _starter = Configure.With(_activator)
                .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "tx-text"))
                .Create();
        }

        static IEnumerable<Scenario> GetScenarios() => new Scenario[]
        {
            new(ThrowException: false, EnlistInScope: true, CompleteTheScope: true, ExpectToReceiveMessage: true)
        };

        [TestCaseSource(nameof(GetScenarios))]
        public async Task SendsMessageOnlyWhenTransactionScopeIsCompleted(Scenario scenario)
        {
            var (throwException, enlistInScope, completeTheScope, expectToReceiveMessage) = scenario;

            using var gotMessage = new ManualResetEvent(initialState: false);

            _activator.Handle<string>(async _ => gotMessage.Set());

            var bus = _starter.Start();
            var publisher = new BusPublisherWithIssue(bus);

            try
            {
                

                if (enlistInScope)
                {
                    await publisher.BeginTransactionAsync();
                }

                await publisher.SendAsync("hallå i stuen!1");

                if (throwException)
                {
                    throw new ApplicationException("omg what is this?????");
                }

                if (completeTheScope)
                {
                    await publisher.CommitAsync();
                }
            }
            catch (ApplicationException exception) when (exception.Message == "omg what is this?????")
            {
                Console.WriteLine("An exception occurred... quite expected though");
            }

            Assert.That(gotMessage.WaitOne(TimeSpan.FromSeconds(1)), Is.EqualTo(expectToReceiveMessage),
                $@"Given the scenario 
    {scenario}
we expected that the message {(expectToReceiveMessage ? "WOULD be RECEIVED" : "would NOT BE RECEIVED")}");
        }

        public record Scenario(bool ThrowException, bool EnlistInScope, bool CompleteTheScope, bool ExpectToReceiveMessage);
    }`


My abstraction:

`
    public class BusPublisherWithIssue 
    {
        private readonly IBus _rebus;
        private TransactionScope _transactionScope;

        public BusPublisherWithIssue(IBus rebus)
        {
            _rebus = rebus;
        }

        public Task SendAsync(object command, CancellationToken token = default)
        {
            return _rebus.SendLocal(command);
        }

        public Task BeginTransactionAsync(CancellationToken token = default)
        {
            if (AmbientTransactionContext.Current == null)
            {
                _transactionScope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
                _transactionScope.EnlistRebus();
            }
            return Task.CompletedTask;
        }

        public Task CommitAsync(CancellationToken token = default)
        {
            _transactionScope?.Complete();
            return Task.CompletedTask;
        }

        public void RollBack()
        {
        }
    }`

**Comment by mookid8000** [comment]
So what difference do you think your abstraction brings with it?

**Comment by mouradchama** [comment]
I think it works only if you have all your code inside the using block like this:

	using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
	{
		scope.EnlistRebus();
	
		// this one is automatically enlisted in the ambient .NET transaction
		await _bus.Send("ostemad");
	
		scope.Complete();
	}

I modified your test class to reproduce the issue without my abstraction:

        private TransactionScope _transactionScope;
        .....

        [TestCaseSource(nameof(GetScenarios))]
        public async Task SendsMessageOnlyWhenTransactionScopeIsCompleted(Scenario scenario)
        {
            var (throwException, enlistInScope, completeTheScope, expectToReceiveMessage) = scenario;

            using var gotMessage = new ManualResetEvent(initialState: false);

            _activator.Handle<string>(async _ => gotMessage.Set());

            var bus = _starter.Start();

            try
            {
                await BeginTransaction(enlistInScope);

                await bus.SendLocal("hallå i stuen!1");
                try
                {

                    if (throwException)
                    {
                        throw new ApplicationException("omg what is this?????");
                    }

                    if (completeTheScope)
                    {
                        _transactionScope.Complete();
                    }

                }
                finally
                {
                    _transactionScope.Dispose();
                }
            }
            catch (ApplicationException exception) when (exception.Message == "omg what is this?????")
            {
                Console.WriteLine("An exception occurred... quite expected though");
            }

            Assert.That(gotMessage.WaitOne(TimeSpan.FromSeconds(1)), Is.EqualTo(expectToReceiveMessage),
                $@"Given the scenario 
    {scenario}
        we expected that the message {(expectToReceiveMessage ? "WOULD be RECEIVED" : "would NOT BE RECEIVED")}");
        }

        private async Task BeginTransaction(bool enlistInScope)
        {
            _transactionScope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

            if (enlistInScope)
            {
                _transactionScope.EnlistRebus();
            }
        }

In this example I removed the using block, which is the case when you want to put your code behind a UnitOfWork.

**Comment by mouradchama** [comment]
Any news about this issue please?

**Comment by mookid8000** [comment]
I think the problem is that you're starting the `TransactionScope` inside an `async` method.

`TransactionScope` flows by being copied along with the execution context to child contexts, but child contexts are not copied back.

This means that it will only flow from the current execution and out (i.e. to async method calls initiated from the execution context that holds the transaction scope), and so you cannot make it work when you start it in an execution context that is a child.

A possible solution is to make the method that creates the transaction scope an ordinary `void` method. If you need to do async stuff, this should also work:

```csharp
// not that this is not async!
private Task BeginTransaction(bool enlistInScope)
{
    // we're still on the original thread and execution context here!
    _transactionScope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

    if (enlistInScope)
    {
        _transactionScope.EnlistRebus();
    }

    // pass Task back to the caller and let the async fun begin
    return InnerBeginTransaction();
}

private async Task InnerBeginTransaction()
{
    // you can await stuff in here
}
```

**Comment by mouradchama** [comment]
Great thank you, it's working in a synchronous context, I don't realy need a task, I converted my method to an avoid method.
