### ISSUE TITLE
v3 is not available on Nuget.org

### ISSUE THREAD

**Issue by trreeves** [rebus-org/Rebus.TransactionScopes#2]
v2 is available, but not v3 : https://www.nuget.org/packages/Rebus.TransactionScope/

v4 is available : https://www.nuget.org/packages/Rebus.TransactionScopes/

**Comment by mookid8000** [comment]
funny..... I can fix that in 30 seconds....

**Comment by mookid8000** [comment]
it's pushed to nuget.org now

**Comment by mookid8000** [comment]
as Rebus.TransactionScope (without the 's') 3.0.1

**Comment by mookid8000** [comment]
thanks for reporting this 😄

**Comment by trreeves** [comment]
great, thanks for the quick response!
