### ISSUE TITLE
Why Rebus.TransactionScopes 4.0.1 was not released to nuget?

### ISSUE THREAD

**Issue by xhafan** [rebus-org/Rebus.TransactionScopes#3]
When using Rebus 5 and latest nuget version Rebus.TransactionScopes 3.0.1, when calling transactionScope.EnlistRebus(), it gives me an exception "Could not load type 'Rebus.Transport.DefaultTransactionContextScope' from assembly 'Rebus, Version=5.0.0.0" (as version Rebus.TransactionScopes 3.0.1 references Rebus 3). When using Rebus.TransactionScopes 4.0.1 (https://github.com/rebus-org/Rebus.TransactionScopes/releases/tag/4.0.1, manually built), it works fine.

My scenario, which works fine with Rebus.TransactionScopes 4.0.1 and msmq transport, is following:

1) asp.net mvc controller method is called within a transaction scope (with rebus enlisted into the transaction scope - transactionScope.EnlistRebus()), controller method processes some business logic in a DB transaction (enlisted in the transaction scope), and sends a message to a service app (_bus.Send(message)).
2) when the business logic fails, the message is not sent correctly.

This scenario works fine with NServiceBus out of the box, and I was looking for an alternative free service bus library which supports this scenario. But, I had to manually build Rebus.TransactionScopes 4.0.1 instead downloading it from nuget.

I'm wondering why Rebus.TransactionScopes 4.0.1 was not released to nuget? Is it not stable or reliable enough?

**Comment by mookid8000** [comment]
> I'm wondering why Rebus.TransactionScopes 4.0.1 was not released to nuget?

When I search for Rebus.TransactionScopes on NuGet.org I get this:

![image](https://user-images.githubusercontent.com/32968/39728252-66a22436-5256-11e8-9206-61d7a7000157.png)

Were you not able to find 4.0.1 on NuGet.org? 😎 

>  Is it not stable or reliable enough?

I think it is stable enough 😉

**Comment by xhafan** [comment]
Thanks, my bad, I was looking at https://www.nuget.org/packages/Rebus.TransactionScope instead of https://www.nuget.org/packages/Rebus.TransactionScopes ('s' at the end)

**Comment by mookid8000** [comment]
Yeah, that’s pretty confusing 🙃 sorry

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com
