### ISSUE TITLE
.NET Standard (& Core) instead of .NET Framework

### ISSUE THREAD

**Issue by kasparkallas** [rebus-org/Rebus.TransactionScopes#5]
Currently the package is dependent on .NET Framework but could be ported to .NET Standard without too much hassle I think.

**Comment by mookid8000** [comment]
A package targeting both .NET 4.5.1 and .NET Standard 2.0 is out as Rebus.TransactionScopes 4.1.1.

Thanks for bringing this to my attention 😄
