### ISSUE TITLE
TransactionScope is not picked up when used in combination with Rebus.TransactionScopes

### ISSUE THREAD

**Issue by thomasdc** [rebus-org/Rebus.TransactionScopes#6]
I'm using `Rebus.SqlServer` in combination with `Rebus.TransactionScopes` to make sure that `bus.Send(...)` commands are processed as one transaction inside a message handler and that an exception thrown **after** a send causes the message not to be queued since the transaction is rollbacked.

However, this doesn't seem to be the case when using `Rebus.SqlServer` as a transport layer.

I use `enlistInAmbientTransaction` (from `Rebus.SqlServer`) and `options.HandleMessagesInsideTransactionScope()` (from `Rebus.TransactionScopes`) so I expect that persisting the message happens in the TransactionScope created by the `TransactionScopeIncomingStep`. It seems as if the pipeline steps are executed **after** the DbConnection was fetched to persist the message so that the TransactionScope is not picked up.

Am I making any sense?
If you want I can reproduce the issue by writing a failing integration test.

**Comment by thomasdcses** [comment]
@mookid8000 Jep, that did it! Thanks a lot! 👍

**Comment by thomasdc** [comment]
@mookid8000 Jep, that did it! Thanks a lot! 👍
