### ISSUE TITLE
await call in handler makes Transaction.Current lose its context

### ISSUE THREAD

**Issue by thomasdc** [rebus-org/Rebus.TransactionScopes#7]
When `await`ing code in a handler that's decorated with an ambient `TransactionScope`, `Transaction.Current` looses its context.
Probably it's because of [this line](https://github.com/rebus-org/Rebus.TransactionScopes/blob/9c975fdbce996c6d21ccbab64736768e5b7ce203/Rebus.TransactionScopes/TransactionScopes/Step.cs#L33) that reassigns `Transaction.Current`. I guess the `TransactionScopeAsyncFlowOption` isn't maintained when using the setter on `Transaction.Current`.

As mentioned [here](https://docs.microsoft.com/en-us/dotnet/api/system.transactions.transaction.current?view=netframework-4.8) `Transaction.Current` is ThreadStatic and all code should preferably manipulate an ambient context via a `using` statement on `TransactionScope`.

I have a [failing test](https://github.com/thomasdc/Rebus.TransactionScopes/commit/80fdc9094a637605f2d7ba40557aa4e2e478ecbf) that reproduces the issue.

Can you confirm the bug?
Is there a reason you removed the using statement in [this commit](https://github.com/rebus-org/Rebus.TransactionScopes/commit/76b59cf1db3b5c02ae43a0aec49c0cd276bda13d)?

**Comment by thomasdc** [comment]
I have a small Linqpad script reproducing the problem:

```
async Task Main()
{
	Thread.CurrentThread.ManagedThreadId.Dump("before await");
	var scope = new TransactionScope(TransactionScopeOption.Required, TransactionScopeAsyncFlowOption.Enabled);
	var transaction = Transaction.Current;
	
	await Task.Delay(1000).ConfigureAwait(false);
	
	Thread.CurrentThread.ManagedThreadId.Dump("after first await");
	Transaction.Current = transaction;
	Transaction.Current.Dump(); // not null
	
	await Task.Delay(1000).ConfigureAwait(false);
	
	Thread.CurrentThread.ManagedThreadId.Dump("after second await");
	Transaction.Current.Dump(); // is null :/
}
```

**Comment by mookid8000** [comment]
Damn. As the commit comment says, the change made the transport's receive operation be executed within a transaction scope too... so e.g. if you were using the SQL transport, then you could enlist all of your work in the same transaction.

Do you have any ideas on how this could be fixed?

**Comment by mookid8000** [comment]
Btw I see you posted the issue with `Transaction.Current` [on StackOverflow too](https://stackoverflow.com/q/55955218/6560)... even Stephen Cleary seems surprised by this behavior 😁

**Comment by thomasdcses** [comment]
I managed to fix the unit test by adding a new TransactionScope wrapping the Transaction you refer to via `ITransactionContext`:

```
class TransactionScopeIncomingStep : IIncomingStep
    {
        ...
        public async Task Process(IncomingStepContext context, Func<Task> next)
        {
            ...
            using (var scope = new TransactionScope(transaction, TransactionScopeAsyncFlowOption.Enabled))
            {
                await next();
            }
        }
    }
```

However, the scope never completes and the message is never marked as processed.

**Comment by thomasdc** [comment]
I managed to fix the unit test by adding a new TransactionScope wrapping the Transaction you refer to via `ITransactionContext`:

```
class TransactionScopeIncomingStep : IIncomingStep
    {
        ...
        public async Task Process(IncomingStepContext context, Func<Task> next)
        {
            ...
            using (var scope = new TransactionScope(transaction, TransactionScopeAsyncFlowOption.Enabled))
            {
                await next();
            }
        }
    }
```

However, the scope never completes and the message is never marked as processed.

**Comment by thomasdc** [comment]
See the [reference commit](https://github.com/thomasdc/Rebus.TransactionScopes/commit/c16769f95c8c0885c87dc17944e8ac2f1430e47a) where I tried to fix the issue.
The unit test now passes, but throws internally:

![](https://i.imgur.com/Huj22Yi.png)

I'm really clueless on this one.
