### ISSUE TITLE
Rebus.TransactionScopes is not compatible with Rebus 6.0.0

### ISSUE THREAD

**Issue by DavidZidar** [rebus-org/Rebus.TransactionScopes#9]
Hi, while trying to upgrade to Rebus I noticed that Rebus.TransactionScopes is not compatiable with version 6 due to a breaking change in the arguments of `ITransactionContext.OnCompleted` and `ITransactionContext.OnDisposed`. The delegate signatures have changed from `Func<Task>` and `Action` to `Func<ITransactionContext, Task>` and `Action<ITransactionContext>` respectively, so a new version of Rebus.TransactionScopes needs to be released with these changes made.

While investigating this issue I noticed two other minor issues as well:
* There is a .NET Framework reference to `System.Transactions` that should be conditional, it is already included in `netstandard2.0` so it results in a build warning
* Both the link and the badge referencing the NuGet-package are incorrect, they are both referencing the old unlisted package `Rebus.TransactionScope`

I have prepared a [branch in a fork](https://github.com/DavidZidar/Rebus.TransactionScopes/compare/master...upgrade-and-fixes) with working fixes for all three issues and could send a pull request unless you want to fix these issues yourselves.

**Comment by mookid8000** [comment]
PR is very welcome 🙂
